apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: rest
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: rest
      chapter: istio
      topic: traffic-management
      version: v1
  replicas: 3 # tells deployment to run 1 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: rest
        chapter: istio
        topic: traffic-management
        version: v1
    spec:
      containers:
      - name: rest-container
        image: sanish/restaurant
        ports:
        - containerPort: 8080
